server {
    listen 80;
    server_name glonass-bot.ru;

    location /api/ {
        proxy_pass http://gate:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /adminer/ {
        proxy_pass http://adminer:8080/;
        proxy_set_header Host $host;
    }

    location /local/ {
        proxy_pass http://minio:9000;
        proxy_set_header Host $http_host;
    }
}