name: "app"

networks:
  glonass_cluster:
    external: true

x-app: &app
  restart: unless-stopped
  volumes:
    - ./envs:/server/envs:ro
  deploy:
    resources:
      limits:
        cpus: "1.0"
        memory: 1.5G
      reservations:
        cpus: "0.25"
        memory: 512M
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "3"


x-app-build: &app-build
  context: ..
  dockerfile: ./docker/gate/Dockerfile

x-common-env: &common-env
  DATABASE_URL: ${DATABASE_URL}
  S3_URL: ${S3_URL}
  S3_USER: ${S3_USER}
  S3_PASSWORD: ${S3_PASSWORD}

services:
  gate:
    <<: *app
    container_name: gate
    hostname: ${GATE_HTTP_HOST}
    build:
      <<: *app-build
      args:
        SERVICE_NAME: gate
    command: ["bun", "dist/apps/gate/main.js"]
    environment:
      <<: *common-env
    ports:
      - "${GATE_HTTP_PORT}:${GATE_HTTP_PORT}"

    depends_on:
      - postgres
      - redis
      - minio
      - nginx
    networks:
      - glonass_cluster

  bot:
    <<: *app
    container_name: bot
    build:
      <<: *app-build
      args:
        SERVICE_NAME: bot
    command: ["bun", "dist/apps/bot/main.js"]
    environment:
      <<: *common-env
    depends_on:
      - postgres
      - redis
      - minio
      - nginx
    networks:
      - glonass_cluster
