name: "infrastructure"

networks:
  glonass_cluster:
    external: true

services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: always
    environment:
      - TUNNEL_TOKEN=eyJhIjoiZDljZGEzOWY5ZTllZWUzMTljMDMzOWZlY2MzNTE3ZjIiLCJ0IjoiNmRjZWUyNTQtNzkxOC00YzhlLWEzNDUtNGY3OGUxYWE5OGU4IiwicyI6Ik5HTXdNekpoWXpBdE1HVTNNUzAwTWpsaExUazJZVE10TVRVNVlUTXpaVFZoWWpVMSJ9
    command: tunnel --no-autoupdate run --protocol http2
    networks:
      - glonass_cluster

  postgres:
    image: postgres:17
    container_name: ${DATABASE_HOST}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ../.deploy/data/postgres:/var/lib/postgresql/data
      - ./postgres/setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro
    networks:
      - glonass_cluster

  adminer:
    image: adminer:5.3.0-standalone
    container_name: adminer
    depends_on:
      - postgres
    networks:
      - glonass_cluster

  redis:
    image: redis:7
    container_name: redis
    networks:
      - glonass_cluster

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${S3_USER}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    command: server /data --console-address ":${S3_UI_PORT}" --address ":${S3_PORT}"
    volumes:
      - ../.deploy/data/minio:/data
    networks:
      - glonass_cluster

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - minio
      - adminer
    networks:
      - glonass_cluster